RESULTS = Li01a.ce Li01a.ci Li01a.en\
          Li01a.rr Li01a.tr\
          Li02a.ai Li02a.ce Li02a.ci Li02a.en\
          Li02a.rr Li02a.tr\
	  Li01a_t00d0i1.rt Li01a_t00d0i2.rt\
	  Li01a_t01d0i1.rt Li01a_t01d0i2.rt\
	  Li01a_t02d0i1.rt Li01a_t02d0i2.rt\
	  Li01a_t03d0i1.rt Li01a_t03d0i2.rt\
	  Li01a_t04d0i1.sp Li01a_t04d0i2.sp\
	  Li02a_t00d0i1.sp Li02a_t00d0i2.sp\
	  Li02a_t01d0i1.sp Li02a_t01d0i2.sp\
	  Li02a_t02d0i1.sp Li02a_t02d0i2.sp\
	  Li02a_t03d0i1.sp Li02a_t03d0i2.sp\
	  Li02a_t04d0i1.sp Li02a_t04d0i2.sp
	  
all:
	python li.py
	python spec.py

	
include ../Make.common
